[[cursos]]
assessor_slugs = ["lilian-maria-penteado-de-arruda-zamith"; "lourdes-degrandis"]
dataiso = "2026-04-23"
titulo = "Vida Religiosa Feminina em tempos de travessia"
descricao = ["""Em um contexto marcado por profundas transformações culturais, eclesiais e comunitárias, a Vida Religiosa Consagrada feminina é chamada a atravessar novos cenários com lucidez, maturidade humana e enraizamento espiritual. Este curso propõe um itinerário formativo que integra corpo, subjetividade, relações comunitárias e processos existenciais, reconhecendo a travessia como lugar de crescimento, discernimento e renovação da missão.
Ao longo de quatro encontros, serão aprofundadas dimensões essenciais da vida consagrada hoje: o corpo como morada e expressão da vida; o cuidado integral da saúde física, mental e espiritual; a vida comunitária como espaço de fraternidade e também de tensões, com atenção aos abusos e à gestão de conflitos; e o envelhecer feminino como tempo de ressignificação, sabedoria e plenitude.
A proposta visa favorecer maior consciência pessoal e comunitária, fortalecer a identidade vocacional e qualificar as relações e a missão, à luz de uma espiritualidade encarnada, integradora e humanizadora.
"""]
cartaz = "img/curso-2026-04-23.png"
link_inscricao = "https://forms.gle/T1QA5qRtfFaBXiZKA"
online = true
# Para o caso de horário e local personalizados utilize as seguintes variaveis:
# Detalhes no arquivo componentes/lista_de_cursos.pug
# Como a data para exibicao e criacao do link de agenda sao diferentes eh
# necessario manter hora e minuto em variaveis independentes
horaInicio = 9
minInicio = 0
horaFim = 12
minFim = 0
local = "Sede do Instituto Acolher - ITA"

