[[cursos]]
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]
dataiso = "2022-11-19"
titulo = "Posturas Narcisistas: vocações do sacrifício e vocações do espetáculo"
descricao = """Hoje encontramos muitas vocações que valorizam mais a beleza
externa do que o bem moral.  Padres e freiras no palco ou no altar, fazendo
shows, reunindo multidões. Religiosos e religiosas que buscam o próprio
reconhecimento mais do que serviço ao outro. Nos bastidores dessas atitudes
existe muito sofrimento, decepção e até doenças, como a depressão. Essas são as
posturas narcisistas que fazem parte do mundo contemporâneo onde o ser humano
precisa aparecer e ser reconhecido para sentir que existe."""
cartaz = "img/curso-2022-11-19.png"
link_inscricao = "https://forms.gle/WVoJ17TyJ2S9yvpE7"
online = true


[[cursos]]
dataiso = "2022-10-21"
titulo = "O suicídio no contexto da Vida Religiosa e Presbiteral: Acolher para prevenir!"
cartaz = "img/simp-2022-10-21.png"
link_inscricao = "https://forms.gle/ahHqzP1cdDy71Lcq9"
online = true


[[cursos]]
assessor_slugs = ["lourdes-degrandis"]
assessor_slugs = ["lilian-maria-penteado-de-arruda-zamith"]
dataiso = "2022-10-08"
titulo = "O corpo que habito"
descricao = """Falar do nosso corpo é falar da integração corpo-mente-
espirito, é falar da vida, é pensar na importância do autoconhecimento,
é perceber um corpo em evolução, crescimento e transformação. Aceitar o corpo
é fundamental para compreender a morada viva do self. Participar do encontro:
O corpo que habito é entrar em contato com a sua morada.  Venha
e experimente..."""
cartaz = "img/curso-2022-10-08.png"
link_inscricao = "https://forms.gle/3KGkpotea4BHbr2a6"
online = true

    
[[cursos]]
assessor_slugs = ["elizete-moura-dos-santos"]
dataiso = "2022-09-17"
titulo = "Maturação da vida afetiva na Vida Religiosa Consagrada"
descricao = """O Papa Francisco, na Mensagem para o 56º Dia Mundial das
Comunicações Sociais-2022, aborda o tema Escutar com o ouvido do coração.
A ênfase fundamental na escuta, leva-nos a refletir que a Vida Religiosa
Consagrada, em sua fundamental opção por Cristo e pela humanidade, torna-se,
por excelência, comprometida com uma permanente maturação da vida afetiva,
possibilitando que os consagrados(as), possam desenvolver sempre mais uma
escuta de si para um acolhimento mais profundo do outro. Desse modo, para
desenvolver uma melhor capacidade de escuta, à luz dos valores evangélicos,
a Ir. Elizete Santos, fsp, psicóloga e associada do ITA, percorrer o seguinte
itinerário: Reconhecer, identificar e acolher os sentimentos; Compreender os
vínculos necessários e possíveis na VRC; Partilhar e integrar os afetos
humanos."""
cartaz = "img/curso-2022-09-17.png"
link_inscricao = "https://forms.gle/b6xk89CnyJ2RXk72A"
online = true


[[cursos]]
dataiso = "2022-07-16"
titulo = "Um olhar para si: o curador ferido, superando angústias e fragilidades"
assessor_slugs = ["wellington-heleno-da-silva"]
descricao = """O sofrimento psíquico é hoje um dos grandes males que acometem
os sacerdotes e religiosos. É necessário um olhar de cuidado para cada um que
sofre. Partindo das noções básicas sobre pulsões, libido e da realidade humana
do presbítero e religioso, abordaremos o dinamismo e a força da sexualidade
e o conflito dos desejos que podem provocar o sofrimento e o esgotamento
emocional, tendo em vista o sentido da vida para uma vivência integradora
e criativa da afetividade e espiritualidade."""
cartaz = "img/curso-2022-07-16.png"
link_inscricao = "https://forms.gle/EaC2JSLxkSh73SG29"
online = true


[[cursos]]
dataiso = "2022-06-25"
titulo = "Tipos Psicológicos"
assessor_slugs = ["flavia-moreira-ribeiro"]
descricao = """Carl Gustav Jung, em sua Teoria da Personalidade, construiu
tipologias ligadas ao ser humano e ao mundo, definidas a partir de estilos
cognitivos e de comportamento individual. Seu modelo tipológico é baseado na
visão de arquétipos ligada a psicologia analítica. E, de modo geral, ele
classificou em quatro tipos principais que são: pensamento ou sentimento,
sensação ou intuição. Sendo que, estes são divididos em classes de saber
racional (ou julgamento) ou irracional (ou perceptivas). A compreensão da
tipologia, além de favorecer o autoconhecimento e melhorar o relacionamento
interpessoal, ajuda a compreender situações de organização de grupos, detecção
e solução de conflitos, treinamento e remanejamento de grupos, criação de
programas de ensino, orientação de pais e professores, orientação vocacional,
aconselhamento familiar e comunitário."""
cartaz = "img/curso-2022-06-25.gif"
link_inscricao = "https://forms.gle/mw4ZE4dVnXigVpdNA"
online = true


[[cursos]]
dataiso = "2022-05-18"
titulo = "Psicólogos do ITA na Diocese de Piracicaba-SP"
assessor_slugs = ["maria-de-fatima-rolim-rosa"]
assessor_slugs = ["wellington-heleno-da-silva"]
descricao = """O Instituto Acolher-ITA realizou em maio de 2022 um encontro
formativo com os padres da Diocese de Piracicaba. O tema proposto, “Um olhar
para si: superando angústias e fragilidades”, procurar abordar de forma
realista as dificuldades no dia-a-dia dos sacerdotes e apontar caminhos para
a compreensão, aceitação e superação desses desafios. Lá estão os psicólogos
e membros do Instituto Acolher Fátima Rolim Rosa e Wellington Heleno da Silva.
É o início de um trabalho que conta com o estímulo do bispo Dom Devair Araújo
da Fonseca e das psicólogas que atuam na diocese. Eles perceberam a necessidade
de dar uma atenção maior à formação dos padres e pediram o apoio do ITA nesse
trabalho."""
cartaz = "img/piracicaba-2022-05-18.png"
online = false


[[cursos]]
dataiso = "2022-05-14"
titulo = "Ansiedade: Defesa ou Defeito?"
assessor_slugs = ["enio-brito-pinto"]
descricao = """Como diferenciar a ansiedade normal, existencial, da ansiedade
patológica? Dialogar com nossas ansiedades é caminho de cuidado e coragem para
bem viver."""
cartaz = "img/curso-2022-05-14.png"
link_inscricao = "https://forms.gle/cwqdggks8UxKYePBA"
online = true


[[cursos]]
dataiso = "2022-04-23"
titulo = "Suicídio no Sacerdócio: Um olhar de Esperança"
assessor_slugs = ["eduardo-augusto-galindo-de-lima"]
descricao = """Nesse curso iremos trabalhar o fenômeno do suicídio que no
Brasil que a cada 45 minutos ceifou a vida de uma pessoa no ano passado.
E a cada morte ocorreram outras 20 tentativas. O suicídio não é um ato
voluntário e livre. É uma consequência do desamparo, do isolamento e dos
transtornos mentais. O sofrimento existencial é uma realidade não partilhada de
sacerdotes e consagrados que sentem o esgotamento mental no seu ministério.
Diante dessa situação dolorosa devemos auxiliar na promoção das ações para
valorização da vida e do bem estar na área humano-afetiva."""
cartaz = "img/curso-2022-04-23.png"
link_inscricao = "https://forms.gle/sDkib3KSRq7NiFLk6"


[[cursos]]
dataiso = "2022-03-19"
titulo = "Relacionamentos na Vida Consagrada e Sacerdotal"
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]
descricao = """Relacionamentos na Vida Consagrada e Sacerdotal<br>Assessor: pe.
Adalberto Wojciech Mittelstaedt, svd <br>(psicólogo e psicopedagogo, mestre em
Teologia, doutor em Ciências da Religião) <br>Maioria dos psicólogos afirma que
o bem estar de uma pessoa depende intrinsecamente do sentimento de amor que ela
experienciou na sua vida desde a infância. Relacionamentos nos quais nos
sentimos amados são portanto necessários para a nossa felicidade e, ainda mais,
para podermos expressar nosso amor diante dos outros. <br>Para uma pessoa
consagrada ou um sacerdote essa experiência é indispensável para sua
realização, ou seja para felicidade na sua missão. E contrário...<br>O
sacerdote, que alguns dias atrás chocou Brasil por se suicidar dentro da
igreja, apontou na sua carta de despedida que se sentiu excluído, desprezado
e desprotegido por outros sacerdotes. Não sabemos muito sobre a sua
enfermidade, mas as queixas apontam reclamações os relacionamentos com os que
deveriam ser mais próximos. """
cartaz = "img/curso-2022-03-19a.jpg"


[[cursos]]
dataiso = "2022-07-16"
titulo = "Afetividade/sexualidade"
assessor_slugs = ["wellington-heleno-da-silva"]


[[cursos]]
dataiso = "2022-11-19"
titulo = "Narcisismo"
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]


[[cursos]]
dataiso = "2022-11-26"
titulo = "O despertar da meia-idade"
assessor_slugs = ["flavia-moreira-ribeiro"]


[[cursos]]
dataiso = "2022-12-03"
titulo = "O despertar da meia-idade"
assessor_slugs = ["flavia-moreira-ribeiro"]
cartaz = "img/cursos-email.png"


[[cursos]]
dataiso = "2022-12-10"
titulo = "Burnout_2"
assessor_slugs = ["wellington-heleno-da-silva"]
cartaz = "img/Natal-2024.png"

[[cursos]]
dataiso = "2022-12-11"
titulo = "Burnout"
assessor_slugs = ["wellington-heleno-da-silva"]
cartaz = "img/email-2024-08-24.png"



