[[cursos]]
assessor_slugs = ["wellington-heleno-da-silva"]
dataiso = "2025-03-29"
titulo = "Atualização para Formadores"
descricao = """A missão de formar novos presbíteros e religiosos exige não apenas um sólido conhecimento teórico, 
mas também um aprofundamento no desenvolvimento humano e vocacional. Esta atualização visa capacitar formadores 
para uma atuação mais qualificada, promovendo uma abordagem integral que favoreça tanto o autoconhecimento quanto 
a compreensão das novas gerações de formandos."""
cartaz = "img/curso-2025-03-30.png"
link_inscricao = "https://zfrmz.com/p9Er6KYFWZrezApOSsTj"
online = true
# Para o caso de horário e local personalizados utilize as seguintes variaveis:
# Detalhes no arquivo componentes/lista_de_cursos.pug
# Como a data para exibicao e criacao do link de agenda sao diferentes eh
# necessario manter hora e minuto em variaveis independentes
horaInicio = 9
minInicio = 0
horaFim = 12
minFim = 0
local = "Sede do Instituto Acolher - ITA"

