# Imagens
# =======
#
# Imagens do membros devem ser quadradas e com tamanho superior a 400x400 (idealmente 600x600)
#
# Grupos para classificação:
#  psicoespiritual
#  psicoterapêutico
#  psicanalítico
#  outras
#
# Membros ativos 2021-11-26
# =========================
#
# Anamelia Alvarenga Nascimento
# Ana Paula de Oliveira Chaddad
# Edênio Valle Pe. (vice-presidente honorário)
# Adalberto Wojciech Mittelstaedt
# Enio Brito Pinto
# Flávia Moreira Ribeiro
# Ir. Elizete Moura dos Santos
# Ivan Rodrigues e Silva Filho
# Jyothi Joseph Satyanapalli
# Lillian M. P. de Arruda Zamith
# Lourdes Degrandis
# Maria de Fátima Rolim Rosa
# Maria José Borela
# Maria Ondina da Silva Peruzzo
# Maria Silva Mourão
# Maruzania Soares Dias
# Rosa Eliza da Silva
# Eduardo Augusto Galindo de Lima
# Francisco Glenio de Almeida
# Wellington Heleno da Silva

# Localizacao dos atendimentos
# sp_1, sp_2, bh_1, curitiba_1

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1", "bh_1" ]
grupo = "psicoterapêutico"
avatar = "maria-da-conceicao-machado-silva-rosa.jpg"
masculino = false
slug = "maria-da-conceicao-machado-silva-rosa"
nome = "Maria da Conceição Machado Silva Rosa"
titulo = "Psicóloga Clínica"
CRP = "06/98755"
descricao = """
Possui Especialização em Cuidados Primários em Saúde Mental pela UNIFESP-SP
e Especialização em Psicopatologia e Saúde Pública pela Faculdade de Saúde
Pública – USP."""
areas = [
  "Saúde mental",
  "Psicoterapia individual",
  "Psicologia Clínica",
  "Psicologia Institucional",
  "Psicopatologia e saúde pública"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "neuropsicológico"
avatar = "ana-paula-de-oliveira-chaddad.png"
masculino = false
slug = "ana-paula-de-oliveira-chaddad"
nome = "Ana Paula de Oliveira Chaddad"
titulo = "Neuropsicóloga"
CRP = "06/166592"
descricao = """
Possui Especialização em avaliação neuropsicológica e neuropsicodiagnóstico"""
areas = [
  "Saúde mental",
  "Psicoterapia individual",
  "Avaliação neuropsicológica",
  "Neuropsicodiagnóstico"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "pe" ]
grupo = "psicoterapêutico"
avatar = "ivan-rodrigues-e-silva-filho.jpg"
masculino = true
slug = "ivan-rodigues-e-silva-filho"
nome = "Ivan Rodrigues e Silva Filho"
titulo = "Psicólogo Clínico"
CRP = "11/0668"
descricao = """Ivan Rodrigues é mestre e doutorando em Psicologia Clínica 
e da Saúde e especialista em Avaliação Psicológica. É também professor da 
Faculdade Jesuíta (FAJE) no curso de Especialização em Espiritualidade 
Cristã e Orientação Espiritual. 35 anos de experiência na clínica psicoterápica 
na abordagem existencial fenomenológica, assim como no serviço de Avaliação Psicológica.
Trabalha com assessoria e palestras.
Autor do livro “A Psicologia na vida religiosa e sacerdotal - por uma formação humana de qualidade” pela Ed Loyola.
"""
areas = [
  "Psicoterapia individual",
  "Psicologia Clínica",
  "Avaliação Psicológica",
  "Assessorias e Palestras"
]
[[membros]]
ativo = true
locais_de_atendimento = ["bh_1" ]
grupo = "psicoterapêutico"
avatar = "maria-jose-borela.png"
masculino = false
slug = "maria-jose-borela"
nome = "Maria José Borela"
titulo = "Psicóloga Clínica/ Psicanalista"
CRP = "04/11641"
descricao = """
Pós-graduada em psicopedagogia pela CEPEMG. Foi coordenadora por quartoze anos da Clínica Social Santa Tereza BHTE-MG.
"""
areas = [
  "Psicoterapia Individual - presencial e online",
  "Psicoterapia de Grupo",
  "Vivências - Adolescentes e Adulto"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_2" ]
grupo = "psicoterapêutico"
avatar = "elizete-moura-dos-santos.jpg"
masculino = false
slug = "elizete-moura-dos-santos"
nome = "Ir. Elizete Moura dos Santos"
titulo = "Psicóloga"
CRP = "06/177899"
descricao = """
Licenciada em Filosofia; Psicóloga Clínica; Especialista em Adolescência
e Juventude; Associada ao Corpo Freudiano Escola de Psicanálise de João
Pessoa/PB."""
areas = [
  "Psicologia Clínica",
  "Psicoterapia individual",
  "Formações",
  "Palestras",
  "Coordenação e interação grupal"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "curitiba_1" ]
grupo = "administrativo"
avatar = "paulo-sergio-frederico.jpg"
masculino = true
slug = "paulo-sergio-frederico"
nome = "Paulo Sérgio Frederico"
titulo = "Secretário"
descricao = ""
areas = ["Organização dos eventos"]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "eduardo-augusto-galindo-de-lima.jpg"
masculino = true
slug = "eduardo-augusto-galindo-de-lima"
nome = "Eduardo Augusto Galindo de Lima"
titulo = "Psicólogo Clínico"
CRP = "06/82462"
descricao = "Especialista em Psicoterapia Breve"
areas = [
  "Psicoterapia de adultos",
  "Grupos e casal",
  "Workshop",
  "Assessorias de grupos e palestras"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
avatar = "lillian-maria-penteado-de-arruda-zamith.jpg"
grupo = "psicoterapêutico"
masculino = false
slug = "lillian-maria-penteado-de-arruda-zamith"
nome = "Lilian Maria Penteado de Arruda Zamith"
titulo = "Psicóloga clínica e Hospitalar"
CRP = "06/35767-8"
descricao = """
Especialista em Psicologia corporal pelo Instituto Sedes
Sapientiae. Aperfeiçoamento em Psicologia Winnicotiana do Amadurecimento.
TCC – Terapia Cognitiva Comportamental."""
areas = [
  "Psicoterapia individual",
  "Casais",
  "Grupos",
  "Vivências",
  "Cursos",
  "Palestras"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicanalítico"
avatar = "francisco-glenio-de-almeida.jpg"
masculino = true
slug = "francisco-glenio-de-almeida"
nome = "Francisco Glenio de Almeida"
titulo = "Psicoterapeuta"
CRP = ""
descricao = """
Formado em filosofia (Unifai), Teologia (N. Sra. Assunção), Aconselhamento
e Orientação familiar. Pós-graduado em Psicoterapia Psicanalitica
(Cepsi-Unip)."""
areas = [
  "Atendimento individual",
  "Atendimento familiar",
  "Atendimento de casais",
  "Psicoterapia psicanalítica"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "lourdes-degrandis.jpg"
masculino = false
slug = "lourdes-degrandis"
nome = "Lourdes Degrandis"
titulo = "Psicóloga Clínica"
CRP = "06/35768-6"
descricao = """
Psicóloga Clínica com especialização em Psicoterapia Corporal pelo Instituto
Sedes Sapientiae, Psicossomática pelo Instituto Sedes Sapientiae, EMDR
(Dessensibilizarão e Sensibilização através de movimentos Oculares) pela
Sociedade Brasileira e Libero Americana de EMDR e Neuropsicologia pelo CDN
- Centro de Diagnóstico Neuropsicológico - UNIFSP."""
areas = [
  "Atendimento de adultos (individual e grupos)",
  "Assessoria a instituições",
  "Workshop",
  "Cursos",
  "Palestras"
]
notas = [
  "Artigo na Revista Convergência",
  "Trabalho sobre Gerações- Formadores - PUC-SP e ITESP",
  "Formadores - OSIB",
  "Formadores - CRB-SP",
  "Juninter - CRB-SP"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "x"
avatar = "maria-de-fatima-naves.jpg"
masculino = false
slug = "maria-de-fatima-naves"
nome = "Mária de Fátima Naves"
titulo = "Psicóloga Clínica"
CRP = "06/40520-0"
descricao = """
Especialização em Análise Transacional, Psicodrama e Psicanálise das
Configurações Vinculares."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Coordenação de grupos de reflexão em Psicanálise dos Vínculos",
  "Integração grupal"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "maria-de-fatima-rolim-rosa.jpg"
masculino = false
slug = "maria-de-fatima-rolim-rosa"
nome = "Maria de Fátima Rolim Rosa"
titulo = "Psicóloga Clínica"
CRP = "06/34959-7"
descricao = """
Especialização e aperfeiçoamento em Gestalt-Terapia, Psicologia Junguiana
e Corporal, Psicologia Winnicotiana e Psicanálise das Configurações
Vinculares."""
areas = [
  "Psicoterapia Individual",
  "Psicoterapia de grupal",
  "Workshop",
  "Assessoria a instituições",
  "Acompanhamento de grupos",
  "Cursos",
  "Palestras"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "maria-ondina-da-silva-peruzzo.jpg"
masculino = false
slug = "maria-ondina-da-silva-peruzzo"
nome = "Maria Ondina da Silva Peruzzo"
titulo = "Especialista em Psicologia Clínica"
CRP = "06/23032"
descricao = """
Especialização em coordenação de grupos e grupoterapia, membro efetivo do
NESME. Especialização em Rorscharch e outras técnicas projetivas; membro
efetivo da Sociedade Brasileira de Rorschach."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Psicodiagnóstico individual",
  "Psicodiagnóstico de grupo",
  "Assessoria de grupos em instituições"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "maria-silva-mourao.jpg"
masculino = false
slug = "maria-silva-mourao"
nome = "Maria Silva Mourão"
titulo = "Especialista em Psicologia Clínica"
CRP = "06/16774"
descricao = """
Mestre em Psicologia Clínica pela PUC-SP; especialista em espiritualidade pela
Gregoriana – Roma; artigos publicados na área da Vida Religiosa Consagrada. Foi
membro da Equipe de Reflexão dos psicólogos da CRB Nacional por quatorze
anos."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Assessorias a congregações religiosas"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "maruzania-soares-dias.jpg"
masculino = false
slug = "maruzania-soares-dias"
nome = "Maruzânia Soares Dias"
titulo = "Psicanalista / Psicóloga Clinica"
CRP = "06/53301-7"
descricao = """
Mestre em Ciências da Religião PUC-SP; graduada em Psicologia pela PUC-SP;
membro da IF-EPFCL – Fórum SP (Internacional dos Fóruns – Escola de Psicanálise
dos Fóruns do Campo Lacaniano – Fórum São Paulo)."""
areas = [
  "Atendimento clínico",
  "Assessorias a grupos e instituições",
  "Conferências"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "wellington-heleno-da-silva.jpg"
masculino = true
slug = "wellington-heleno-da-silva"
nome = "Wellington Heleno da Silva"
titulo = "Psicólogo Clínico"
CRP = "06/10292"
descricao = """
Especialização em Psicoterapia Psicanalítica – CEPSI/UNIP; MBA em Gestão de
Pessoas e Liderança – BSP (Business School of São Paulo); Graduado em Teologia,
Instituto Pio XI; Curso de Filosofia no Instituto Filosófico do Mosteiro de São
Bento; Curso de Psicologia de Grupo e Aconselhamento de Adolescentes e Jovens.
Membro efetivo do Instituto Acolher – ITA."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo (adolescentes, adultos e casais)",
  "Grupos psicanalíticos de reflexão e discussões",
  "Palestras e assessorias de formação para grupos e instituições"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "wojciech-mittelstaedt-adalberto.jpg"
masculino = true
slug = "wojciech-mittelstaedt-adalberto"
nome = "Wojciech Mittelstaedt (Adalberto)"
titulo = "Psicopedagogo / Psicólogo Clínico"
CRP = "06/99753"
descricao = """
Padre da Congregação do Verbo Divino; Doutor em Ciências da Religião (PUC/SP)
com enfoque em Psicologia da Religião; Mestre em Teologia pela Universidade
KUL, na Polônia; graduado em Psicologia (Universidade São Marcos – SP);
especializado em Psicopedagogia; aperfeiçoamento em tratamento da Dependência
Química pela UNIFESP; Membro do Instituto Acolher – ITA."""
areas = [
  "Psicologia clínica",
  "Assessorias",
  "Palestras",
  "Formação religiosa",
  "Espiritualidade sacerdotal",
  "Renovação religiosa",
  "Tratamento dos vícios"
]




[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "outras"
avatar = "jyothi-joseph-satyanapalli.jpg"
masculino = false
slug = "jyothi-joseph-satyanapalli"
nome = "Jyothi Joseph Satyanapalli"
titulo = "Massoterapêuta"
descricao = """
Missionária indiana do PIME, tem 
contato com a massagem desde criança, 
quando aplicava as técnicas em seus 
pais e avós"""
areas = [
  "Massoterapia", 
  "Drenagem linfática",
  "Quick massagem",
  "Bambu terapia",
  "Pedras quentes",
  "Modelação",
  "Redução",
  "Limpeza facial", 
  "Terapia Eletromagnético",
  "Reflexologia",
  "Floral de Bach"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "leonel-gomes-da-silva.jpg"
masculino = true
slug = "leonel-gomes-da-silva"
nome = "Leonel Gomes da Silva"
titulo = "Psicólogo"
CRP = "06/220757"
descricao = """
Master em Psicologia do Desenvolvimento da criança e do Adolescente pela Universidade de Santiago de Compostela 
Especializacao em Neuropsicologia pela Faculdade Rui Barbosa, Salvador, BA. Graduação em Filosofia pela FAJE,
Graduação em Teologia pela FaJe. Graduando em Psicologia pela Mackenzie."""
areas = [
  "Orientação Educacional",
  "Pastoral",
  "Projetos Sociais"
]
areas_es = [
 "Orientación educativa",
 "Pastoral",
 "Proyectos sociales"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "outras"
avatar = "marilda-santos-de-souza.jpg"
masculino = true
slug = "marilda-santos-de-souza"
nome = "Marilda Santos de Souza"
titulo = "Bacharel em Psicologia"
CRP = "x"
descricao = """
"""
areas = [
  "x",
  "y"
]



[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "sergio-lucas-camara.jpg"
masculino = true
slug = "sergio-lucas-camara"
nome = "Sérgio Lucas Câmara"
titulo = "Psicólogo"
CRP = "06/107924"
descricao = """
Padre e pároco da Arquidiocese de São Paulo, Doutor em Psicologia Clínica pela PUC de São Paulo, 
Mestrado em Psicologia Clínica pela PUC de São Paulo, Mestre em Teologia Pastoral pela UNIFAI de São Paulo.
Publicações: CAMARA, S. L.; VALE, T.G. Assistência espiritual. In: CASTILHO, R. K.; SILVA, V.C.S.; PINTO, C.S. 
Manual de Cuidados Paliativos da Academia Nacional de Cuidados Paliativos - ANCP, 3ª. ed. Rio de Janeiro: Atheneu, 2021.
CAMARA, S. L; VALE, T. G.; BASSANI, M. A. A preparação dos padres para lidarem com a situação de morte no Brasil: 
uma revisão documental e crítica. Revista de Cultura Teológica. São Paulo, n. 93, pp. 322-347, 2019."""
areas = [
  "Psicoterapia com enlutados",
  "Psicologia Clínica"
]

[[membros]]
ativo = true
locais_de_atendimento = [ "sp_1" ]
grupo = "psicoterapêutico"
avatar = "vagner-sanagiotto.jpg"
masculino = true
slug = "vagner-sanagiotto"
nome = "Vagner Sanagiotto"
titulo = "Psicólogo"
CRP = "08/23984"
descricao = """
Doutor em Psicologia pela Pontificia Università Salesiana (Roma, Itália), teólogo e filósofo. 
Tem como área de pesquisa a Psicopatologia na Vida Religiosa e Presbiteral. 
"""
areas = [
  "Vida Religiosa",
  "Logoterapia",
  "Ciências da Religião",
  "História e Cultura da Religião",
  "Theology of religious (consecrated life)",
  "Lived Religion and Religious Practice in Everyday Life",
  "Priesthood",
  "Priestly Writings"
]
